name: flutter_mvvm_boilerplate
description: A new Flutter project.

# `flutter pub publish`
publish_to: "none"

# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

# `flutter pub upgrade --major-versions`
# `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0
  package_info_plus: ^3.0.1
  desktop_window: ^0.4.0
  easy_localization: ^3.0.1
  google_fonts: ^3.0.1
  dynamic_color: ^1.5.4
  logger: ^1.1.0
  copy_with_extension: ^4.0.4
  json_annotation: ^4.7.0
  cloud_firestore: ^4.0.4
  firebase_core: ^2.1.1
  flutter_phoenix: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  copy_with_extension_gen: ^4.0.4
  json_serializable: ^6.5.4
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
